### ISSUE TITLE
Fixing a correct coverage.xml results in inconsistent coverage.xml

### ISSUE THREAD

**Issue by hugobuddel** [omegacen/coverage-fixpaths#1]
In directory `/opt/project`, the root of the project:

* `coverage.original.xml`, created with `coverage run -m pytest src/micado/test/functional/containedint_test.py` (file renamed)
* `coverage.fixedpaths.xml`, created with `coverage-fixpaths coverage.original.xml --out coverage.fixedpaths.xml`

See [coverages.zip](https://github.com/omegacen/coverage-fixpaths/files/4551674/coverages.zip)

```
/opt/project> head -n 12 coverage.original.xml
[...]
        <sources>
                <source>/opt/project</source>
        </sources>
        <packages>
                <package branch-rate="0" complexity="0" line-rate="1" name="src.micado">
                        <classes>
                                <class branch-rate="0" complexity="0" filename="src/micado/__init__.py" line-rate="1" name="__init__.py">

/opt/project> head -n 12 coverage.fixedpaths.xml
[...]
        <sources>
                <source>/opt/project/src/micado</source></sources>
        <packages>
                <package branch-rate="0" complexity="0" line-rate="1" name="src.micado">
                        <classes>
                                <class branch-rate="0" complexity="0" filename="src/micado/__init__.py" line-rate="1" name="__init__.py">
```

The `sources` have been updated, but the `filenames` have not:

* Original: `/opt/project` + `src/micado/__init__.py` = `/opt/project/src/micado/__init__.py`, which is correct.
* Fixedpaths: `/opt/project/src/micado` + `src/micado/__init__.py` = `/opt/project/src/micado/src/micado/__init__.py`, which is incorrect.

**Comment by teake** [comment]
Thanks for the report!
